apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: web-crawler-parser
        image: maor30levy/web-crawler-parser:latest
        ports:
        - containerPort: 5050
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: PARSER_PORT