apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: web-crawler-server
        image: maor30levy/web-crawler-server:latest
        ports:
        - containerPort: 4000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: SERVER_PORT
          - name: WORKER_PORT
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: WORKER_PORT
          - name: WORKER_HOST
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: WORKER_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: REDIS_PORT
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: REDIS_HOST
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: AWS_SECRET_ACCESS_KEY